name: Search Agent Workflow

on:
  workflow_dispatch:
    inputs:
      query:
        description: '用户查询问题'
        required: true
      callback_url:
        description: '回调URL（用于发送结果）'
        required: true

jobs:
  run-search-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run search agent
        env:
          JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          QUERY: ${{ github.event.inputs.query }}
          CALLBACK_URL: ${{ github.event.inputs.callback_url }}
        run: |
          python src/gh_action_runner.py